### ISSUE TITLE
Summarize and Document common themes

### ISSUE THREAD

**Issue by RoseRelevo** [data2health/nlp-review#16]

**Comment by RoseRelevo** [comment]
I have standardized the coding of the abstracted data.  Table three shows the "codes" for lack of a better word in three categories, the source of the text, the task being performed and the outcome measures.  (I've also got some unspecified items that will require a further look).  I would like for us to think about the best way to summarize this information, in a table format, as a results presentation.

Meanwhile also be thinking on threads and themes to inform our narrative results sections.

**Comment by adrzell** [comment]
Hi Rose,
I’ve blocked out all day Thursday to work on NLP, with our meeting in the middle. I was on vacation last week, but I can’t wait to see what you have done!
Adrienne

**Comment by RoseRelevo** [comment]
Adrienne is currently writing up the results for the source of text categorization
