### ISSUE TITLE
Develop Figure

### ISSUE THREAD

**Issue by RoseRelevo** [data2health/nlp-review#18]
potentially display:
geographic distribution
# authors
# countries
# states
# institutions
# departments
major funders

**Comment by RoseRelevo** [comment]
Large font is an artifact of my use of the hashtag to indicate "number of" whoops

**Comment by jmcmurry** [comment]
Please don't assign this to me until I have the source data to do something with this :)

**Comment by RoseRelevo** [comment]
> Please don't assign this to me until I have the source data to do something with this :)

No Problem, learning the systems

**Comment by RoseRelevo** [comment]
another thing we could look at is numbers of accuracy only studies vs. others

a mapping of the could would should sort of abstracts might be interesting

I've also got all those tables in my working document at various levels of granularity of context

**Comment by RoseRelevo** [comment]
If you look at Columns A-V of this table
https://docs.google.com/spreadsheets/d/1qHPp-9vWhWJ24SqkE8dY8_Po8wTfm5wYu_4mp1qr01o/edit#gid=0 

I'm looking for advise that would help to visualize this funding and institutional information, I have abstracted all the data, and can answer any questions
