### ISSUE TITLE
Develop Inclusion and Exclusion Criteria

### ISSUE THREAD

**Issue by RoseRelevo** [data2health/nlp-review#28]
This is a formal document spelling out what will be included in a review and what won't.  Developing this a priori is one of the hallmarks of a systematic review.

**Comment by mellybelly** [comment]
Great, please make sure a google doc is linked or document uploaded into the github.

**Comment by RoseRelevo** [comment]
> Great, please make sure a google doc is linked or document uploaded into the github.

currently, all of it is jammed together in "working document" ; first I'm gonna go through all of the closed milestones to granulize the steps and pontificate.  Note the separate notes about documentation for each item.  Then, I'm going to develop the Google docs, both templates and current docs and links. !

**Comment by mellybelly** [comment]
+1!!

**Comment by RoseRelevo** [comment]
Documentation: This should also be developed as an individual document, often the appendix contains the actual working document that is displayed in a bifurcated decision matrix.  This should be part of the protocol as well.  This may be revised along with the searches as well as use and discussion after piloting.  Often additional decision points or clarifications, are needed.

**Comment by RoseRelevo** [comment]
https://drive.google.com/open?id=15Z7jONR8LPub37AHl_z3a16gmNlnkEu8c3QntS_Yq1w 
Posted in Google Docs
