### ISSUE TITLE
Check for concordance

### ISSUE THREAD

**Issue by RoseRelevo** [data2health/nlp-review#59]
there are 23 articles in the RefWorks folder marked "RESOLVE"

please look at them and include or exclude based on the title and abstract

this is a double check of our inter-rater agreement

**Comment by RoseRelevo** [comment]
I've moved this from the DataAbstraction Milestone, because it is not actually holding up any next steps

**Comment by vpejaver** [comment]
Sounds good. Just to clarify, by the end of this, I will have emptied out RESOLVE and placed everything in RESOLVE in either "Included & Abstracted" or "Excluded at Title and Abstract", correct?

**Comment by RoseRelevo** [comment]
Yes, thanks!

have you had a look at the consort flow diagram?
https://docs.google.com/document/d/1mEF_ALkEyPwffYwxZxsnX_JAzShqlbxHM_CS4bg7uww/edit

It might actually help explain the folders better than any narrative.

Thanks again

Rose

**Comment by vpejaver** [comment]
I've finished looking at these, and most of them were excluded. There were three articles that I thought should be included. I've moved those over to the "Included & Abstracted" folder but have not added any information to the spreadsheet. At this stage, should I be doing this or are we discussing the reclassification first?

**Comment by RoseRelevo** [comment]
If you could identify the items that were moved to Included & Abstracted but not yet in the spreadsheet.  I'll have a look at them.

**Comment by vpejaver** [comment]
Alright, here are the three papers that I have not added to the spreadsheet:

1. Branch-Elliman et al. (2015) Natural Language Processing for Real-Time Catheter-Associated Urinary Tract Infection Surveillance: Results of a Pilot Implementation Trial. PMID: 26022228.

2. Carell et al. (2013) Using Natural Language Processing to Improve Efficiency of Manual Chart Abstraction in Research: The Case of Breast Cancer Recurrence. PMID: 24488511.

3. Souvignet et al. (2014) Ci4SeR - Curation Interface for Semantic Resources - Evaluation with Adverse Drug Reactions. PMID: 25160157.

Let me know if I can close this issue.
