### ISSUE TITLE
Abstract Data Reviewer V

### ISSUE THREAD

**Issue by RoseRelevo** [data2health/nlp-review#9]
Abstract the data from articles assigned to Vikas [@jmcmurry added this for clarity]

**Comment by jmcmurry** [comment]
Not sure what this means; is it assigning a reviewer? Completion of the reviews?

**Comment by RoseRelevo** [comment]
oh there are three reviewers, Each needs to abstract data from their pile
of articles. V=Vikas

**Comment by RoseRelevo** [comment]
Clarification from Vikas - this is done
